version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: async-jobs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  rabbitmq:
    image: rabbitmq:3-management
    container_name: async-jobs-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build:
      context: .
      dockerfile: infrastructure/docker/api.Dockerfile
    container_name: async-jobs-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/jobs
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8000:8000"
    command: >
      uv run uvicorn apps.api.app:app
      --host 0.0.0.0
      --port 8000
      --reload
    volumes:
      - .:/app

  worker:
    build:
      context: .
      dockerfile: infrastructure/docker/worker.Dockerfile
    container_name: async-jobs-worker
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/jobs
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    command: >
      uv run python -m apps.worker.main
    volumes:
      - .:/app

  test:
    build:
      context: .
      dockerfile: infrastructure/docker/api.Dockerfile
    container_name: async-jobs-tests
    depends_on:
      - postgres
      - rabbitmq
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/jobs_test
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    command: /app/.venv/bin/pytest -q
    volumes:
      - .:/app

volumes:
  postgres_data: